### PR TITLE
remove golang sdk docs

### PR DESCRIPTION
**Pull request by rajatjindal**

### CODE REVIEW

**Comment by adamreese** [comment]
There is also some docs in the tutorial section

**Comment by adamreese** [comment]
https://github.com/macolso/developer/blob/proj-muon/content/spin/serverless-ai-tutorial.md

**Comment by rajatjindal** [comment]
pls dont merge yet. i've not tested rendering of it. doing that next

**Comment by rajatjindal** [comment]
Tim is making the changes to pull these

**Pull request closed without merging**
